import React from 'react';
import { View, Text, Image, StyleSheet, ScrollView, Touchable, TouchableOpacity } from 'react-native'
import Modal from 'react-native-modal'
import { heightPercentageToDP, widthPercentageToDP } from 'react-native-responsive-screen';


const TermsPopup = (props) => {
    return <Modal
        hasBackdrop={false}
        isVisible={props.isVisible}
        style={{
            margin: 0
        }}>
        <View style={styles.modalBackground}>
            <View style={styles.activityIndicatorWrapper}>
                {/* <ActivityIndicator size="large" color="#FFAD36" /> */}
                <Text style={styles.titleStyle}>Terms and Conditions</Text>
                <ScrollView style={styles.scrollStyle}>
                    <Text style={styles.paragraph}>These Terms & Conditions (“Terms”) of (a) use of our website www.LearnLite.in (“Website”), our applications (“Application”) or any products or services in connection with the Application/,  Website/products (“Services”)  or (b) any modes of registrations or usage of products, including through SD cards, tablets or other storage/transmitting device  are between AllnAll LearnLite (“AllnAll LearnLite /We/Us/Our”) and its users (“User/You/Your”).</Text>
                    <Text style={styles.paragraph}>These Terms constitute an electronic record in accordance with the provisions of the Information Technology Act, 2000 and the Information Technology (Intermediaries guidelines) Rules, 2011 thereunder, as amended from time to time.</Text>
                    <Text style={styles.paragraph}>Please read the Terms and the privacy policy of the AllnAll LearnLite (“Privacy Policy”) with respect to registration with us, the use of the Application, Website,  Services and products carefully before using the Application, Website,  Services or products. In the event of any discrepancy between the Terms and any other policies with respect to the Application or Website or Services or products, the provisions of the Terms shall prevail.</Text>
                    <Text style={styles.paragraph}>Your use/access/browsing of the Application or Website or the Services or products or registration (with or without payment/with or without subscription) through any means shall signify Your acceptance of the Terms and Your agreement to be legally bound by the same.</Text>
                    <Text style={styles.paragraph}>If You do not agree with the Terms or the Privacy Policy, please do not use the Application or Website or avail the Services or products. Any access to our Services/Application/products through registrations/subscription is non transferable.</Text>
                    <Text style={styles.paragraph}>1.Except as mentioned below, all information, content, material, trademarks, services marks, trade names, and trade secrets including but not limited to the software, text, images, graphics, video, script and audio, contained in the Application, Website, Services and products are proprietary property of the AllnAll LearnLite (“Proprietary Information”).  No Proprietary Information may be copied, downloaded, reproduced, modified, republished, uploaded, posted, transmitted or distributed in any way without obtaining prior written permission from the AllnAll LearnLite and nothing on this Application or Website or Services shall be or products deemed to confer a license of or any other right, interest or title to or in any of the intellectual property rights belonging to the AllnAll LearnLite , to the User. You may own the medium on which the information, content or materials resides, but the AllnAll LearnLite shall at all times retain full and complete title to the information, content or materials and all intellectual property rights inserted by the AllnAll LearnLite on such medium. Certain contents on the Website may belong to third parties. Such contents have been reproduced after taking prior consent from said party and all rights relating to such content will remain with such third party. Further, you recognize and acknowledge that the ownership of all trademarks, copyright, logos, service marks and other intellectual property owned by any third party shall continue to vest with such party and You are not permitted to use the same without the consent of the respective third party.</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>2. Your use of our products, Website, Application and Services is solely for Your personal and non-commercial use. Any use of the Application, Website, Services or products or  their contents other than for personal purposes is prohibited. Your personal and non-commercial use of this Application, Website, products and / or our Services shall be subjected to the following restrictions:</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>i. You may not decompile, reverse engineer, or disassemble the contents of the Application and / or our Website and/or Services/ products or modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained from the Application and / or our Website and/or Services/products, or remove any copyright, trademark registration, or other proprietary notices from the contents of the Application and / or and / or our Website and/or Services/products.</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>ii. You will not (a) use this Application and / or our Website and/or any of our product/s or Service/s for commercial purposes of any kind, or (b) advertise or sell the Application or any products, Services or domain names or otherwise (whether or not for profit), or solicit others (including, without limitation, solicitations for contributions or donations) or use any public forum for commercial purposes of any kind, or (c) use the Application and / or Website/our products and Services in any way that is unlawful, or harms the AllnAll LearnLite or any other person or entity as determined by the AllnAll LearnLite .</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>iii. No User shall be permitted to perform any of the following prohibited activities while availing our Services:</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>a. Making available any content that is misleading, unlawful, harmful, threatening, abusive, tortious, defamatory, libelous, vulgar, obscene, child-pornographic, lewd, lascivious, profane, invasive of another's privacy, hateful, or racially, ethnically or otherwise objectionable;</Text>
                    <Text style={[styles.paragraph, { marginBottom: 0 }]}>b. Stalking, intimidating and/or harassing another and/or inciting other to commit violence;</Text>
                    <Text style={[styles.paragraph]}>c. Transmitting material that encourages anyone to commit a criminal offence, that results in civil liability or otherwise breaches any relevant laws, regulations or code of practice;{"\n"}
d. Interfering with any other person's use or enjoyment of the Application/Website/Services;{"\n"}
e. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner, committing any act that amounts to the infringement of intellectual property or making available any material that infringes any intellectual property rights or other proprietary rights of anyone else;{"\n"}
f. Make available any content or material that You do not have a right to make available under any law or contractual or fiduciary relationship, unless You own or control the rights thereto or have received all necessary consents for such use of the content;{"\n"}
g. Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a person or entity;{"\n"}
h. Post, transmit or make available any material that contains viruses, trojan horses, worms, spyware, time bombs, cancel bots, or other computer programming routines, code, files or such other programs that may harm the Application/services, interests or rights of other users or limit the functionality of any computer software, hardware or telecommunications, or that may harvest or collect any data or personal information about other Users without their consent;{"\n"}
i. Access or use the Application/Website/Services/products in any manner that could damage, disable, overburden or impair any of the Application's/Website's servers or the networks connected to any of the servers on which the Application/Website is hosted;{"\n"}
j. Intentionally or unintentionally interfere with or disrupt the services or violate any applicable laws related to the access to or use of the Application/Website/Services/products, violate any requirements, procedures, policies or regulations of networks connected to the Application/Website/Services/products, or engage in any activity prohibited by these Terms;{"\n"}
k. Disrupt or interfere with the security of, or otherwise cause harm to, the Application/Website/Services/products, materials, systems resources, or gain unauthorized access to user accounts, passwords, servers or networks connected to or accessible through the Application/Website/Services/products or any affiliated or linked sites;{"\n"}
l. Interfere with, or inhibit any user from using and enjoying access to the Application/Website/ Services/products, or other affiliated sites, or engage in disruptive attacks such as denial of service attack on the Application/Website/Services/products;{"\n"}
m. Use deep-links, page-scrape, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to increase traffic to the Application/Website/Services/products, to access, acquire, copy or monitor any portion of the Application /Website/Services/products, or in any way reproduce or circumvent the navigational structure or presentation of the Application, or any content, to obtain or attempt to obtain any content, documents or information through any means not specifically made available through the Application/ Website/Services/products;{"\n"}
n. Alter or modify any part of the Services;{"\n"}
o. Use the Services for purposes that are not permitted by: (i) these Terms; and (ii) any applicable law, regulation or generally accepted practices or guidelines in the relevant jurisdiction; or{"\n"}
p. Violate any of the terms specified under the Terms for the use of the Application /Website/Services/products.{"\n"}
                    </Text>
                    <Text style={styles.paragraph}>3.By submitting content on or through the Services (your “Material”), you grant us a worldwide, non-exclusive, royalty-free license (with the right to sublicense) to use, copy, reproduce, process, adapt, modify, publish, transmit, display and distribute such Material in any and all media or distribution methods (now known or later developed) and to associate your Material with you, except as described below. You agree that others may use Your Material in the same way as any other content available through the Services. Other users of the Services may fork, tweak and repurpose your Material in accordance with these Terms. If you delete your user account your Material and name may remain available through the Services</Text>
                    <Text style={styles.paragraph}>4.In the preparation of the Application/Website/Services/products and contents therein, every effort has been made to offer the most current, correct, and clearly expressed information possible. Nevertheless, inadvertent errors may occur. In particular, but without limiting anything here, the AllnAll LearnLite disclaims any responsibility for any errors and accuracy of the information that may be contained in the Application. Any feedback from User is most welcome to make the Application and contents thereof error free and user friendly. AllnAll LearnLite also reserves the right and discretion to make any changes/corrections or withdraw/add contents at any time without notice. Neither the AllnAll LearnLite nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on Application/Website/Services/products for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</Text>
                    <Text style={styles.paragraph}>5.Our Website provides Users with access to compiled educational information and related sources. Such information is provided on an As Is basis and We assume no liability for the accuracy or completeness or use or non obsolescence of such information. We shall not be liable to update or ensure continuity of such information contained on the Website. We would not be responsible for any errors, which might appear in such information, which is compiled from third party sources or for any unavailability of such information. From time to time the Website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s). You may not create a link to the Website from another website or document without the AllnAll LearnLite 's prior written consent.</Text>
                    <Text style={styles.paragraph}>6.The contents of the Application/Services/products are developed on the concepts covered in the structured curriculum syllabus prescribed for students of various courses. The usage of the Application/Services/products is not endorsed as a substitution to the curriculum based education provided by the educational institutions but is intended to supplement the same by explaining and presenting the concepts in a manner enabling easy understanding. The basic definitions and formulae of the subject matter would remain the same. The AllnAll LearnLite acknowledges that there are various means of delivering structured curriculum pedagogy and inclusion of methods in the Application/Services/products does not imply endorsement of any particular method nor exclusion imply disapproval. Subscription to the Application or usage of our Services/Website/products does not in any manner guarantee admission to any educational institutions or passing of any exams or achievement of any specified percentage of marks in any examinations.</Text>
                    <Text style={styles.paragraph}>7.Certain contents in the Application/Services/Website/products (in particular relating to assistance in preparations for administrative services) may contain opinions and views. The AllnAll LearnLite shall not be responsible for such opinions or any claims resulting from them. Further, the AllnAll LearnLite makes no warranties or representations whatsoever regarding the quality, content, completeness, or adequacy of such information and data.</Text>
                    <Text style={styles.paragraph}>8.Some parts of the Services are interactive, and we encourage contributions by Users, which may or may not be subject to editorial control prior to being posted. The AllnAll LearnLite accepts no responsibility or liability for any material communicated by third parties in this way. The AllnAll LearnLite reserves the right at its sole discretion to remove, review, edit or delete any content. Similarly, We will not be responsible or liable for any content uploaded by Users directly on the Website, irrespective of whether We have certified any answer uploaded by the User. We would not be responsible to verify whether such questions/answers or contents placed by any User contain infringing materials or not.</Text>
                    <Text style={styles.paragraph}>9.The AllnAll LearnLite may, based on any form of access to the Application (including free download/trials) or Services or Website or registrations through any source whatsoever, contact the User through sms, email and call, to give information about its products as well as notifications on various important updates and/or to seek permission for demonstration of its products. The User expressly grants such permission to contact him/her through telephone, SMS, e-mail and holds the AllnAll LearnLite indemnified against any liabilities including financial penalties, damages, expenses in case the User's mobile number is registered with Do not Call (DNC) database. By registering yourself , you agree to make your contact details available to Our employees, associates and partners so that you may be contacted for education information and promotions through telephone, SMS, email etc.</Text>
                    <Text style={styles.paragraph}>10.While the AllnAll LearnLite may, based on the User's confirmation, facilitate the demonstration of its products at the location sought by the User, the User acknowledges that he/she has not been induced by any statements or representations of any person with respect to the quality or conditions of the products and that User has relied solely on the investigations, examinations and inspections as the User has chosen to make and that the AllnAll LearnLite has afforded the User the opportunity for full and complete investigations, examinations and inspections.</Text>
                    <Text style={styles.paragraph}>11.Upon registration through any means whatsoever, the AllnAll LearnLite may contact You through the registered mobile number or e-mail or any other mobile number or contact number or email provided by You to enable effective provision of Services. The User expressly permits the AllnAll LearnLite to contact him/her and the student utilising the Services, through the above mentioned means at any time post registration. .-. Further, the AllnAll LearnLite shall have the right to monitor the download and usage of the Application/Services/products and the contents thereof by the User/student, to analyze such usage and discuss the same with the User/student to enable effective and efficient usage of the Services. The User expressly permits the AllnAll LearnLite to clear the doubts of the student using the Application/Services/online portal by answering the questions placed before it, providing study plans, informing of the progress, providing feedback, communicating with the student and mentoring the student through telephone or e-mail on express consent of the legal guardian/parent of the User or through any other forum.</Text>
                    <Text style={styles.paragraph}>12.While the AllnAll LearnLite has made efforts to train the personnel engaged in the sales and services relating to its products to enable quality control, it makes no warranties or representations whatsoever regarding the quality and competence of such personnel and would not be responsible for any deviant behaviour of any such personnel. Any feedback from User relating to the same is most welcome and AllnAll LearnLite reserves the right and discretion to take any action in this regard.</Text>
                    <Text style={styles.paragraph}>13.Access to certain elements of the Services including doubt clearance, mentoring services etc may be subject to separate terms, conditions and fair usage policy. The AllnAll LearnLite reserves the right to determine the criteria for provision of various elements of Services to the different categories of Users based on its policies. Hence, subscription to the Application/products or registrations do not automatically entitle the User to any and all elements of Services provided by the AllnAll LearnLite and the AllnAll LearnLite shall be entitled to exercise its discretion while providing access to and determining continuity of certain elements of Services. We reserve the right to extend, cancel, discontinue, prematurely withdraw or modify any of Our Services at Our discretion.</Text>
                    <Text style={styles.paragraph}>14.The AllnAll LearnLite 's products and / or Services, including the Application and content, are compatible only with certain devices/tablets/instruments/hardware. The AllnAll LearnLite shall not be obligated to provide workable products and / or services for any instruments that are not recognized by the AllnAll LearnLite or those instruments that may be purchased from any third party which are not compatible with the AllnAll LearnLite 's products and Services. The AllnAll LearnLite reserves the right to upgrade the table/ type of compatible devices as required from time to time.</Text>
                    <Text style={styles.paragraph}>15.The AllnAll LearnLite shall have no responsibility for any loss or damage caused to tablet or any other hardware and / or software and/or instrument, including loss of data or effect on the processing speed, resulting from Your use of our products and Services.</Text>
                    <Text style={styles.paragraph}>16.You have to pay online the subscription fee as prescribed by AllnAll LearnLite from time to time for availing the services. The subscription fee once paid shall not be refunded under any circumstances.</Text>
                    <Text style={styles.paragraph}>17.You are subjected to the terms /rules relating to payment gateway prevailing in India and should take all reasonable precautions against online financial frauds, which may be instructed by the Government of India through its regulating bodies from time to time. AllnAll LearnLite shall not be liable for on line financial frauds done by cyber criminals, incase of financial frauds it shall be the responsibility of the subscriber to inform the cyber police and their respective bank immediately.</Text>
                    <Text style={styles.paragraph}>19.In order to access the Services and to avail the use of the Application/products, You shall be required to register yourself with the Application/Services/products, and maintain an account with the Application/Services/products. You will be required to furnish certain information and details, including Your name, mobile number, e-mail address, residential address, grade/class of the student, school name, payment information (credit/debit card details) if required, and any other information deemed necessary by the Application. With respect to the provision of information, the following may be noted:-</Text>
                    
                    <Text style={styles.bulletPoints}><Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>It is Your sole responsibility to ensure that the account information provided by You is accurate, complete and latest.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>You shall be responsible for maintaining the confidentiality of the account information and for all activities that occur under Your account. You agree to (a) ensure that You successfully log out from Your account at the end of each session; and (b) immediately notify the AllnAll LearnLite of any unauthorized use of Your account.  If there is reason to believe that there is likely to be a breach of security or misuse of Your account, we may request You to change the password or we may suspend Your account without any liability to the AllnAll LearnLite , for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>You acknowledge that Your ability to use Your account is dependent upon external factors such as internet service providers and internet network availability and the AllnAll LearnLite cannot guarantee accessibility to the Application at all times. In addition to the disclaimers set forth in the Terms, the AllnAll LearnLite shall not be liable to You for any damages arising from Your inability to log into Your account and access the services of the Application at any time.</Text>
                    <Text style={styles.paragraph}>20.Persons who are "competent/capable" of contracting within the meaning of the Indian Contract Act, 1872 shall be eligible to register for the Application and all Our products or Services. Persons who are minors, un-discharged insolvents etc. are not eligible to register for Our products or Services. As a minor if You wish to use Our products or Services, such use shall be made available to You by Your legal guardian or parents, who has agreed to these Terms. In the event a minor utilizes the Application/Website/Services, it is assumed that he/she has obtained the consent of the legal guardian or parents and such use is made available by the legal guardian or parents. The AllnAll LearnLite will not be responsible for any consequence that arises as a result of misuse of any kind of Our Application or any of Our products or Services that may occur by virtue of any person including a minor registering for the Services/products provided. By using the products or Services You warrant that all the data provided by You is accurate and complete and that student using the Application has obtained the consent of parent/legal guardian (in case of minors). The AllnAll LearnLite reserves the right to terminate Your subscription and / or refuse to provide You with access to the products or Services if it is discovered that You are under the age of 18 (eighteen) years and the consent to use the products or Services is not made by Your parent/legal guardian or any information provided by You is inaccurate. You acknowledge that the AllnAll LearnLite does not have the responsibility to ensure that You conform to the aforesaid eligibility criteria. It shall be Your sole responsibility to ensure that You meet the required qualification. Any persons under the age of 18 (eighteen) should seek the consent of their parents/legal guardians before providing any Information about themselves or their parents and other family members on the Application.</Text>
                    <Text style={styles.paragraph}>21.You agree to defend, indemnify and hold harmless the AllnAll LearnLite , its officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) Your use of and access of the Application/Website/Services; (ii) Your violation of any term of these Terms or any other policy of the AllnAll LearnLite ; (iii) Your violation of any third party right, including without limitation, any copyright, property, or privacy right; or (iv) any claim that Your use of the Application/Website/Services has caused damage to a third party. This defense and indemnification obligation will survive these Terms.</Text>
                    <Text style={styles.paragraph}>22.In no event shall the AllnAll LearnLite , its officers, , employees, partners or agents be liable to You or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits or any other claim arising out, of or in connection with, Your use of, or access to, the Application.</Text>
                    <Text style={styles.paragraph}>23.In the event of Your breach of these Terms, You agree that the AllnAll LearnLite will be irreparably harmed and may not have an adequate remedy in money or damages. The AllnAll LearnLite therefore, shall be entitled in such event to obtain an injunction against such a breach from any court of competent jurisdiction. The AllnAll LearnLite 's right to obtain such relief shall not limit its right to obtain other remedies.</Text>
                    <Text style={styles.paragraph}>24.Any violation by You of the terms of this Clause may result in immediate suspension or termination of Your Accounts apart from any legal remedy that the AllnAll LearnLite can avail. In such instances, the AllnAll LearnLite may also disclose Your Account Information if required by any Governmental or legal authority. You understand that the violation of these Terms could also result in civil or criminal liability under applicable laws.</Text>
                    <Text style={styles.paragraph}>25.The Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of law principles. Further, the Terms shall be subject to the exclusive jurisdiction of the competent courts located in Bangalore and You hereby accede to and accept the jurisdiction of such courts.</Text>
                    <Text style={styles.paragraph}>26.The AllnAll LearnLite has the right to change modify, suspend, or discontinue and/or eliminate any aspect(s), features or functionality of the Application or the Services as it deems fit at any time without notice. Further, the AllnAll LearnLite has the right to amend these Terms from time to time without prior notice to you. The AllnAll LearnLite makes no commitment, express or implied, to maintain or continue any aspect of the Application. You agree that the AllnAll LearnLite shall not be liable to You or any third party for any modification, suspension or discontinuance of the Application/Services. All prices are subject to change without notice.</Text>
                    <Text style={styles.paragraph}>27.DISCLAIMER: THIS WEBSITE, THE APPLICATION AND THE SERVICES ARE PROVIDED ON AN "AS IS" BASIS WITH ALL FAULTS AND WITHOUT ANY WARRANTY OF ANY KIND. THE ALLNALL LEARNLITE HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS WITH REGARD TO THE WEBSITE, APPLICATION/PRODUCTS AND THE SERVICES, INCLUDING WITHOUT LIMITATION, ALL IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, ACCURACY, TIMELINESS. PERFORMANCE, COMPLETENESS, SUITABILITY AND NON-INFRINGEMENT. ADDITIONALLY, THE ALLNALL LEARNLITE SHALL NOT BE LIABLE FOR ANY DAMAGES ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SITE, OR THE APPLICATION OR THE SERVICES. YOUR USE OF ANY INFORMATION OR MATERIALS ON THIS WEBSITE/APPLICATION/SERVICES/PRODUCTS IS ENTIRELY AT YOUR OWN RISK, FOR WHICH WE SHALL NOT BE LIABLE. IT SHALL BE YOUR OWN RESPONSIBILITY TO ENSURE THAT SERVICES PROVIDED BY US MEET YOUR SPECIFIC REQUIREMENTS.</Text>
                    <Text style={styles.paragraph}>28.General Provisions:</Text>
                    <Text style={styles.bulletPoints}><Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Notice: All notices served by the AllnAll LearnLite shall be provided via email to Your account or as a general notification on the Application. Any notice to be provided to the AllnAll LearnLite should be sent to info@LearnLite.in.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Entire Agreement: The Terms, along with the Privacy Policy, and any other guidelines/policies made by AllnAll LearnLite applicable to the Application from time to time, constitute the entire agreement between the AllnAll LearnLite and You with respect to Your access to or use of the Application, Website and the Services thereof.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Assignment: You cannot assign or otherwise transfer Your obligations under the Terms, or any right granted hereunder to any third party. The AllnAll LearnLite 's rights under the Terms are freely transferable by the AllnAll LearnLite to any third parties without the requirement of seeking Your consent.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Severability: If, for any reason, a court of competent jurisdiction finds any provision of the Terms, or portion thereof, to be unenforceable, that provision shall be enforced to the maximum extent permissible so as to give effect to the intent of the parties as reflected by that provision, and the remainder of the Terms shall continue in full force and effect.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Waiver: Any failure by the AllnAll LearnLite to enforce or exercise any provision of the Terms, or any related right, shall not constitute a waiver by the AllnAll LearnLite of that provision or right.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Relationship: You acknowledge that Your participation on the Application, does not make You an employee or agency or partnership or joint venture or franchise of the AllnAll LearnLite .{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>The AllnAll LearnLite provides these Terms so that You are aware of the terms that apply to your use of the Website/Application and Services. You acknowledge that, the AllnAll LearnLite has given You a reasonable opportunity to review these Terms and that You have agreed to them.</Text>
                    <Text style={styles.paragraph}>29.Feedback:</Text>
                    <Text style={styles.bulletPoints}><Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Any feedback You provide with respect to the Application shall be deemed to be non-confidential. The Application shall be free to use such information on an unrestricted basis. Further, by submitting the feedback, You represent and warrant that (i) Your feedback does not contain confidential or proprietary information of You or of third parties; (ii) the AllnAll LearnLite is not under any obligation of confidentiality, express or implied, with respect to the feedback; (iii) the Application may have something similar to the feedback already under consideration or in development; and (iv) You are not entitled to any compensation or reimbursement of any kind from the AllnAll LearnLite for the feedback under any circumstances, unless specified.{"\n"}
                    <Text style={{fontSize:heightPercentageToDP('3%')}}>• </Text>Under no circumstances shall the AllnAll LearnLite be held responsible in any manner for any content provided by other users even such content is offensive, hurtful or offensive. Please exercise caution while accessing the Application.</Text>
                    <Text style={styles.paragraph}>30.Customer Care:We make all best endeavours to provide You with a pleasant experience. In the unlikely event that You face any issues, please contact us: +91 8310136364</Text>
                </ScrollView>
                <TouchableOpacity style={styles.closeButtonStyle} onPress={()=>{
                    props.close()
                }}>
                    <Text style={styles.closeButtonTextStyle}>Close</Text>
                </TouchableOpacity>
            </View>
        </View>
    </Modal>
}

export default TermsPopup

const styles = StyleSheet.create({
    modalBackground: {
        flex: 1,
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'space-around',
        backgroundColor: '#00000040',
    },
    activityIndicatorWrapper: {
        backgroundColor: '#FFFFFF',
        height: heightPercentageToDP('90%'),
        width: widthPercentageToDP('90%'),
        borderRadius: 10,
        display: 'flex',
        alignItems: 'center',
        //   justifyContent: 'space-around',
    },
    titleStyle: {
        fontFamily: 'Sora-Bold',
        color: '#184E76',
        fontSize: heightPercentageToDP('3%'),
        marginVertical: heightPercentageToDP('2%'),
        marginTop:heightPercentageToDP('3%')
    },
    scrollStyle: {
        flex: 1,
        paddingHorizontal: heightPercentageToDP('2.5%')
    },
    closeButtonStyle: {
        height: heightPercentageToDP('5%'),
        width: heightPercentageToDP('12%'),
        backgroundColor: '#C9302C',
        justifyContent: 'center',
        alignItems: 'center',
        marginVertical: heightPercentageToDP('2%')
    },
    closeButtonTextStyle: {
        fontFamily: 'Sora-Bold',
        fontSize: heightPercentageToDP('2%'),
        color: '#fff'
    },
    paragraph: {
        fontSize: heightPercentageToDP('2%'),
        fontFamily: 'Sora-Medium',
        color: '#333',
        textAlign: 'justify',
        marginBottom: heightPercentageToDP('2%')
    },
    bulletPoints:{
        fontSize: heightPercentageToDP('2%'),
        fontFamily: 'Sora-Medium',
        color: '#333',
        textAlign: 'justify',
        marginLeft:heightPercentageToDP('2.5%'),
        marginBottom:heightPercentageToDP('2%')
    }
});