import keyMirror from 'fbjs/lib/keyMirror';

const ActionTypes = keyMirror({
  TOGGLE_HAMBURGER_MENU: 'TOGGLE_HAMBURGER_MENU', 
  SET_NAVIGATION_PARAM:'SET_NAVIGATION_PARAM',
  SET_SELECTED_MONTH:'SET_SELECTED_MONTH',
  SET_SELECTED_SUBJECT:'SET_SELECTED_SUBJECT',
  SET_SELECTED_CHAPTER:'SET_SELECTED_CHAPTER',
  SET_SUBSCRIPTION_STATUS:'SET_SUBSCRIPTION_STATUS',
  SET_USER_DATA:'SET_USER_DATA',
  IS_FREE_TRIAL_ENABLED:"IS_FREE_TRIAL_ENABLED",
  SET_SUBSCRIPTION_DATA : "SET_SUBSCRIPTION_DATA",
  SET_SUBSCRIBED_SUBJECTS : "SET_SUBSCRIBED_SUBJECTS",
  SET_PARENT_DETAILS : "SET_PARENT_DETAILS",
  SET_SUBSCRIBED_MONTH : "SET_SUBSCRIBED_MONTH",
  SET_STUDENT_DETAILS : "SET_STUDENT_DETAILS",
  SET_STUDENT_LIST : "SET_STUDENT_LIST",
  SET_SELECTED_STUDENT_ID : "SET_SELECTED_STUDENT_ID",
  PARENT_SUBSCRIPTION_DETAILS : "PARENT_SUBSCRIPTION_DETAILS"
});

export default ActionTypes;
